name: Elixir CI

on:
  push:
    branches: [ "main",  "11-fix-workflow-elixiryml"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]  


    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get

  test:
    name: Test
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
  
    container:
      image: mysql:8.0
      ports:
        - 3306:3306
      env:
        ImageOS: ubuntu20
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: betunfair_test
        MYSQL_USER: betunfair
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      run: |
        apt-get update
        apt-get install -y curl
        curl -sSL https://github.com/erlef/setup-beam/raw/988e02bfe678367a02564f65ca2e37726dc0268f/dist/install-otp.sh | bash -s -- ubuntu-20.04 OTP-24.1.7
      env:
        OTP_VERSION: '24.1.7'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Initialize Database
      run: mysql -u betunfair -p"${{ secrets.MYSQL_PASSWORD }}" -h 127.0.0.1 < utils/init.sql
  
    - name: Run tests
      run: mix test
    
